name: Upload coverage reports to Codecov
uses: codecov/codecov-action@v3
on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
  workflow_dispatch:
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
